CREATE OR REPLACE PROCEDURE TOPP_LIMPA_AI (P_UNIDADE IN NUMBER, P_NOTA IN NUMBER) IS
BEGIN
	
    DELETE FROM AI_CE_DIARIOS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_ITENS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_NOTAS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_NOTAS_OPERACOES WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_NOTAS_ICMS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
        
    DELETE FROM AI_NS_NOTAS_OBSERVACOES WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_NOTAS_PARCELAS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_NS_NOTAS_SAIDAS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_CR_TITULOS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    DELETE FROM AI_CR_HISTORICOS WHERE COD_UNIDADE = P_UNIDADE AND NUM_NOTA = P_NOTA;
    
    COMMIT;
    
END;