-- 3. TOPT_LINX_COND_PGTO 
-- Tabela de/para para as condições de pagamento
-- Alteracao - Inclusao de id e remocao de chave composta, que passe a ser uma "unique"
DROP TABLE TOPT_LINX_COND_PGTO CASCADE CONSTRAINTS;

CREATE TABLE TOPT_LINX_COND_PGTO (
      ID             NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, SISTEMA        VARCHAR2 (15) NOT NULL
	, CODIGO         NUMBER NOT NULL
	, TIP_TITULO     NUMBER (4) NOT NULL
	, DES_LANCAMENTO VARCHAR2 (150) NOT NULL
	, COD_COND_PGTO  NUMBER (4) NOT NULL
	, DES_COND_PGTO  VARCHAR2 (150) NOT NULL
	, IND_AVISTA     NUMBER (1) NOT NULL
	, COD_PESSOA     NUMBER (7),
	CONSTRAINT LINX_RELAC_COND_PGTO_PK PRIMARY KEY (ID),
	CONSTRAINT LINX_RELAC_COND_PGTO_UK UNIQUE (SISTEMA, CODIGO)
	);
	
-- Server: INVERTER
-- Table:  TOPT_LINX_COND_PGTO
-- Date:   15/03/2022 14:52

INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 87, 55, 'INCLUSAO - CARTAO VISA ELETRON', 70, 'CARTAO ELO', 0, 10003);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 22, 3, 'INCLUSAO - VENDA  A VISTA', 90, 'PAGAMENTO A VISTA VENDA DIRETA', 1, NULL);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 24, 50, 'INCLUSAO - CARTAO VISA', 40, 'CARTAO VISA -  A VISTA', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 25, 50, 'INCLUSAO - CARTAO VISA', 41, 'CARTAO VISA -  2 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 26, 50, 'INCLUSAO - CARTAO VISA', 42, 'CARTAO VISA -  3 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 44, 50, 'INCLUSAO - CARTAO VISA', 43, 'CARTAO VISA -  4 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 45, 50, 'INCLUSAO - CARTAO VISA', 44, 'CARTAO VISA -  5 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 46, 50, 'INCLUSAO - CARTAO VISA', 45, 'CARTAO VISA -  6 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 29, 51, 'INCLUSAO - CARTAO CREDCARD', 50, 'CARTAO CREDCARD - A VISTA', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 30, 51, 'INCLUSAO - CARTAO CREDCARD', 51, 'CARTAO CREDCARD - 2 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 52, 51, 'INCLUSAO - CARTAO DINNERS', 55, 'DINERS 6X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 47, 51, 'INCLUSAO - CARTAO CREDCARD', 53, 'CARTAO CREDCARD - 4 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 48, 51, 'INCLUSAO - CARTAO CREDCARD', 54, 'CARTAO CREDCARD - 5 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 49, 51, 'INCLUSAO - CARTAO CREDCARD', 55, 'CARTAO CREDCARD - 6 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 54, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 60, 'CARTAO AMERICAN EXPRESS - A VISTA', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 55, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 61, 'CARTAO AMERICAN EXPRESS - 2 VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 56, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 62, 'CARTAO AMERICAN EXPRESS - 3  VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 57, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 63, 'CARTAO AMERICAN EXPRESS - 4  VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 58, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 64, 'CARTAO AMERICAN EXPRESS - 5  VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 59, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 65, 'CARTAO AMERICAN EXPRESS - 6  VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 43, 55, 'INCLUSAO - CARTAO VISA ELETRON', 70, 'CARTAO VISA  ELETRON', 0, 10003);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 27, 56, 'INCLUSAO - CARTAO REDE SHOP', 71, 'CARTAO REDE SHOP', 0, 10004);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 61, 51, 'INCLUSAO - CARTAO CREDCARD', 50, 'CARTAO CREDCARD - A VISTA(OFFLINE)', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 60, 55, 'INCLUSAO - CARTAO VISA ELETRON', 70, 'CARTAO VISA  ELETRON (OFFLINE)', 0, 10003);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 63, 50, 'INCLUSAO - CARTAO VISA', 40, 'CARTAO VISA -  A VISTA (OFFLINE)', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 62, 56, 'INCLUSAO - CARTAO REDE SHOP', 71, 'CARTAO REDE SHOP (OFFLINE)', 0, 10004);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 42, 69, 'MULTIPAGAMENTO', 74, 'MULTIPAGAMENTO', 0, 10009);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 35, 51, 'INCLUSAO - CARTAO DINNERS', 50, 'DINERS 1X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 67, 69, 'MULTIPAGAMENTO', 74, 'MULTIPAGAMENTO(OFFLINE)', 0, 10009);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 36, 51, 'INCLUSAO - CARTAO DINNERS', 51, 'DINERS 2X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 37, 51, 'INCLUSAO - CARTAO DINNERS', 52, 'DINERS 3X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 66, 51, 'INCLUSAO - CARTAO DINNERS', 50, 'CARTAO DINNERS  (OFFLINE)', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 31, 51, 'INCLUSAO - CARTAO CREDCARD', 52, 'CARTAO CREDCARD - 3 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 50, 51, 'INCLUSAO - CARTAO DINNERS', 43, 'DINERS 4X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 51, 51, 'INCLUSAO - CARTAO DINNERS', 54, 'DINERS 5X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 68, 67, 'BONIFICADO', 90, 'BONIFICADO', 1, NULL);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 53, 3, 'INCLUSAO - VENDA  A VISTA', 90, 'DEPOSITO ANTECIPADO', 1, NULL);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 73, 50, 'INCLUSAO - CARTAO VISA', 46, 'CARTAO VISA -  7 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 74, 50, 'INCLUSAO - CARTAO VISA', 47, 'CARTAO VISA -  8 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 75, 50, 'INCLUSAO - CARTAO VISA', 48, 'CARTAO VISA -  9 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 76, 50, 'INCLUSAO - CARTAO VISA', 49, 'CARTAO VISA - 10 VEZES', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 81, 51, 'INCLUSAO - CARTAO CREDCARD', 66, 'CARTAO CREDCARD - 7 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 82, 51, 'INCLUSAO - CARTAO CREDCARD', 67, 'CARTAO CREDCARD - 8 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 83, 51, 'INCLUSAO - CARTAO CREDCARD', 68, 'CARTAO CREDCARD - 9 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 84, 51, 'INCLUSAO - CARTAO CREDCARD', 56, 'CARTAO CREDCARD - 10 VEZES', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 77, 51, 'INCLUSAO - CARTAO DINNERS', 66, 'DINERS 7X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 78, 51, 'INCLUSAO - CARTAO DINNERS', 67, 'DINERS 8X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 79, 51, 'INCLUSAO - CARTAO DINNERS', 68, 'DINERS 9X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 80, 51, 'INCLUSAO - CARTAO DINERS', 56, 'DINERS 10X', 0, 10001);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 69, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 81, 'CARTAO AMERICAN EXPRESS - 7 VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 70, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 82, 'CARTAO AMERICAN EXPRESS - 8 VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 71, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 83, 'CARTAO AMERICAN EXPRESS - 9 VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 72, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 84, ' CARTAO AMERICAN EXPRESS - 10 VEZES', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 65, 52, 'INCLUSAO - CARTAO AMERICAN EXPRESS', 60, 'CARTAO OFFLINE AMEX', 0, 10002);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('PCI', 85, 57, 'INCLUSAO - DEVOLUÇAO', 22, 'DEVOLUÇAO DE VENDA', 1, NULL);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('MICROVIX', 70, 50, 'INCLUSAO - CARTAO VISA', 40, 'CARTAO VISA -  A VISTA', 0, 10000);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('MICROVIX', 80, 55, 'INCLUSAO - CARTAO VISA ELETRON', 70, 'CARTAO VISA  ELETRON', 0, 10003);
INSERT INTO TOPT_LINX_COND_PGTO (SISTEMA, CODIGO, TIP_TITULO, DES_LANCAMENTO, COD_COND_PGTO, DES_COND_PGTO, IND_AVISTA, COD_PESSOA) VALUES ('MICROVIX', 144, 3, 'INCLUSAO - VENDA  A VISTA', 90, 'PAGAMENTO A VISTA VENDA DIRETA', 1, NULL);
